apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-pv
  namespace: openhands
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /tmp/workspace