apiVersion: v1
kind: Service
metadata:
  name: openhands-app-service
  namespace: openhands
spec:
  selector:
    app: openhands-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer